/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fr.ubordeaux.ao;

import javax.swing.*;
import java.awt.event.*;
import java.io.IOException;

public class App extends JFrame {
    /**
     *
     */
    private static final long serialVersionUID = 1L;

    public App() {
        super("SVG tester");
        WindowListener l = new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                System.exit(0);
            }
        };
        addWindowListener(l);
        setSize(800, 900);
    }

    public static void main(String[] args) {
        JFrame window = new App();
        JPanel panel = new JPanel();
        Line l = new Line(new Point2D(500, 500), new Point2D(800, 800));
        Ellipse e = new Circle(new Point2D(150, 200), 100);
        Rectangle r = new Rectangle(new Point2D(300, 400), 20, 30);
        SVG svg = new SVG(800, 900);
        svg.add(e);
        svg.add(l);
        svg.add(r);
        try {
            svg.save("test.svg");
        } catch (IOException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
        }
        JTextArea text = new JTextArea(r.toSVG());
        panel.add(text);
        window.add(panel);
        window.setVisible(true);
    }
}
